sipelu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user_handle.urls")),
    path('detail/', include("lukisan_handle.urls"))
]

user_handle/urls.py
from django.urls import path, include
from .views import *

app_name = "user"

urlpatterns = [
    path('', landing, name="landing"),

    path('login_staff', login_staff, name="login_staff"),
    path('logout_staff', logout_staff, name="logout_staff"),
    path('list_pengguna', list_pengguna, name="list_pengguna"),
    path('list_staff', list_staff, name="list_staff"),
    path('list_bank', list_mitra_bank, name="list_bank"),
    path('add_bank', add_mitra_bank, name="add_bank"),
    path('delete_bank/<id>', delete_bank, name="delete_bank"),

    path('login', login_pelanggan, name="login"),
    path('logout', logout_pelanggan, name="logout"),
    path('signup_pemilik', daftar_pelanggan_pemilik, name="signup_pemilik"),
    path('signup_penyewa', daftar_pelanggan_penyewa, name="signup_penyewa"),
    path('profile_staff/<id>', profile_staff, name="profile_staff"),
    path('profile/<id>', profile, name="profile")
]

user_handle/models.py
from django.db import connection
from django.contrib.auth.hashers import make_password, check_password


class Staff():

    cursor = None

    def __init__(self, *args, **kwargs):
        self.cursor = connection.cursor()
        self.cursor.execute("SET SEARCH_PATH TO sipelu")

    def getAll(self):
        self.cursor.execute(
            "SELECT s.*, sl.* FROM staff s join staff_lulusan sl on s.no_staff = sl.no_staff")
        res = self.serialize(self.cursor)
        return res

    def get_profile(self, id):
        self.cursor.execute(
            "SELECT * FROM staff WHERE no_staff = %s", [id])
        res = self.serialize(self.cursor)
        return res[0]

    def authenticate(self, id, password):
        self.cursor.execute(
            "SELECT no_staff,nama,no_hp,email,password FROM staff WHERE no_staff= %s", [id])
        res = self.serialize(self.cursor)

        if (len(res) > 0 and check_password(password, res[0]["password"])):
            return res[0]
        return None

    def get_penyewa(self):
        self.cursor.execute(
            "SELECT pl.*, pn.* FROM pelanggan pl join penyewa pn on pl.id_pelanggan = pn.id_pelanggan")
        res = self.serialize(self.cursor)
        return res

    def get_pemilik(self):
        self.cursor.execute(
            "SELECT pl.*, pk.* FROM pelanggan pl join pemilik pk on pl.id_pelanggan = pk.id_pelanggan")
        res = self.serialize(self.cursor)
        return res

    def get_sewa(self):
        self.cursor.execute(
            "select a.*, b.* from (select ts.*, bs.* from transaksi_sewa ts join biaya_sewa bs on ts.tgl_sewa = bs.tgl_sewa) a join (select tb.*, mb.* from tenor_bayar tb join mitra_bank mb on tb.kode_bank = mb.kode_bank ) b on a.kode_tenor = b.kode_tenor"
        )
        res = self.serialize(self.cursor)
        return res

    def get_transaksi(self):
        self.cursor.execute(
            "select f.tgl_terima, f.jumlah, f.id_pelanggan, l.harga, (l.harga * f.jumlah) as total from fee f join lukisan l on f.id_pelanggan = l.id_pelanggan;")
        res = self.serialize(self.cursor)
        return res

    def create_super_user(self):
        self.cursor.execute("UPDATE staff SET nama=%s, password= %s WHERE no_staff = %s", [
            "Anggardha Febriano", make_password("test12345"), "STF0000001"])

    def serialize(self, cursor):
        "Return all rows from a cursor as a dict"
        columns = [col[0] for col in cursor.description]
        return [
            dict(zip(columns, row))
            for row in cursor.fetchall()
        ]


class Pelanggan():

    cursor = None

    def __init__(self, *args, **kwargs):
        self.cursor = connection.cursor()
        self.cursor.execute("SET SEARCH_PATH TO sipelu")

    def getAll(self):
        self.cursor.execute("SELECT * FROM pelanggan")
        res = self.serialize(self.cursor)
        return res

    def get_profile(self, id):
        self.cursor.execute(
            "SELECT * FROM pelanggan WHERE id_pelanggan = %s", [id])
        res = self.serialize(self.cursor)
        return res[0]

    def generate_id(self):
        all_user = len(self.getAll())
        new_user = str(all_user + 1)
        zero = ""
        for i in range(len(new_user), 7):
            zero += "0"

        return "USR" + zero + new_user

    def create_pelanggan_pemilik(self, nama, password, no_ktp, alamat, ttl, email, no_hp, no_rek, nama_bank):
        id = self.generate_id()
        self.cursor.execute("INSERT INTO pelanggan VALUES (%s,%s,%s,%s,%s,%s,%s,%s)", [
            id, no_ktp, nama, alamat, ttl, no_hp, email, make_password(password)])

        self.cursor.execute("INSERT INTO pemilik VALUES (%s, %s, %s)", [
                            id, no_rek, nama_bank])

    def create_pelanggan_penyewa(self, nama, password, no_ktp, alamat, ttl, email, no_hp, pekerjaan, kategori):
        id = self.generate_id()
        self.cursor.execute("INSERT INTO pelanggan VALUES (%s,%s,%s,%s,%s,%s,%s,%s)", [
            id, no_ktp, nama, alamat, ttl, no_hp, email, make_password(password)])

        self.cursor.execute("INSERT INTO penyewa VALUES (%s, %s, %s)", [
                            id, pekerjaan, kategori])

    def create_super_user(self):
        with connection.cursor() as cursor:
            cursor.execute("SET SEARCH_PATH TO sipelu")
            cursor.execute("UPDATE pelanggan SET nama=%s, password= %s WHERE id_pelanggan = %s", [
                           "Anggardha Febriano", make_password("test12345"), "USR0000001"])

    def authenticate(self, id, password):
        self.cursor.execute(
            "SELECT * FROM pelanggan WHERE id_pelanggan= %s", [id])
        res = self.serialize(self.cursor)

        if (len(res) > 0 and check_password(password, res[0]["password"])):
            return res[0]
        return None

    def check_role(self, id):
        self.cursor.execute(
            "SELECT id_pelanggan, CASE WHEN id_pelanggan IN (SELECT id_pelanggan FROM pemilik WHERE id_pelanggan = %s) THEN True else False end as pemilik from pelanggan where id_pelanggan = %s", [
                id, id]
        )
        res = self.serialize(self.cursor)

        return res

    def serialize(self, cursor):
        "Return all rows from a cursor as a dict"
        columns = [col[0] for col in cursor.description]
        return [
            dict(zip(columns, row))
            for row in cursor.fetchall()
        ]


class Bank():

    cursor = None

    def __init__(self, *args, **kwargs):
        self.cursor = connection.cursor()
        self.cursor.execute("SET SEARCH_PATH TO sipelu")

    def serialize(self, cursor):
        "Return all rows from a cursor as a dict"
        columns = [col[0] for col in cursor.description]
        return [
            dict(zip(columns, row))
            for row in cursor.fetchall()
        ]

    def getAll(self):
        self.cursor.execute(
            "SELECT * FROM mitra_bank"
        )
        res = self.serialize(self.cursor)

        return res

    def create_mitra(self, nama_bank):
        new_id = self.generate_id()
        self.cursor.execute(
            "INSERT INTO mitra_bank values (%s, %s)", [new_id, nama_bank]
        )

    def delete_mitra(self, id):
        self.cursor.execute(
            "DELETE FROM mitra_bank WHERE kode_bank = %s", [id]
        )

    def generate_id(self):
        all_mitra = len(self.getAll())
        new_mitra = str(all_mitra + 1)
        zero = ""
        for i in range(len(new_mitra), 3):
            zero += "0"

        return "B" + zero + new_mitra

user_handle/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from lukisan_handle.models import Lukisan
from user_handle.models import Staff, Pelanggan, Bank
from user_handle.decorator import login_required
import json
import datetime


def landing(request):
    lukisan_list = Lukisan().getAll()
    paginator = Paginator(lukisan_list, 5)
    page = request.GET.get('page')
    lukisan = paginator.get_page(page)
    return render(request, "landing/landing.html", {
        "lukisan": lukisan
    })


def login_staff(request):

    if request.method == "POST":

        staff_id = request.POST["staff_id"]
        password = request.POST["password"]
        staff = Staff().authenticate(staff_id, password)
        if staff:

            request.session["user"] = json.dumps(staff)
            request.session["staff"] = staff["no_staff"]
            request.session.modified = True

    return redirect("user:landing")


@login_required
def list_pengguna(request):

    pemilik = Staff().get_pemilik()
    penyewa = Staff().get_penyewa()
    bank = Bank().getAll()

    return render(request, "user_handle/list_pengguna.html", {
        "list_pemilik": pemilik,
        "list_penyewa": penyewa,
        "list_bank": bank
    })


@login_required
def list_staff(request):

    staff = Staff().getAll()

    return render(request, "user_handle/list_staff.html", {
        "list_staff": staff
    })


@login_required
def logout_staff(request):
    try:
        del request.session['staff']
        del request.session['user']
    except KeyError:
        pass
    return redirect("user:landing")


def default(o):
    if isinstance(o, (datetime.date, datetime.datetime)):
        return o.isoformat()


def login_pelanggan(request):

    if request.method == "POST":

        user_id = request.POST["user_id"]
        password = request.POST["password"]
        user_obj = Pelanggan()
        user = user_obj.authenticate(user_id, password)
        if user:
            user["pemilik"] = user_obj.check_role(user_id)[0]["pemilik"]
            request.session["user"] = json.dumps(user,
                                                 sort_keys=True,
                                                 indent=1,
                                                 default=default)
            request.session["pemilik"] = user["pemilik"]
            request.session.modified = True

    return redirect("user:landing")


@login_required
def profile_staff(request, id):

    user = Staff().get_profile(id)

    print(user)

    return render(request, "user_handle/profile.html", {
        "user": user
    })


def daftar_pelanggan_pemilik(request):

    if request.method == "POST":

        user_obj = Pelanggan()
        print(request.POST)
        name = request.POST["nama"]
        email = request.POST["email"]
        password = request.POST["password"]
        no_ktp = request.POST["no_ktp"]
        raw_ttl = request.POST["ttl"]
        no_hp = request.POST["no_hp"]
        alamat = request.POST["alamat"]
        no_rek = request.POST["no_rek"]
        nama_bank = request.POST["bank"]

        user = user_obj.create_pelanggan_pemilik(
            name, password, no_ktp, alamat, raw_ttl, email, no_hp, no_rek, nama_bank)

    return redirect("user:list_pengguna")


def daftar_pelanggan_penyewa(request):

    if request.method == "POST":

        user_obj = Pelanggan()

        name = request.POST["nama"]
        email = request.POST["email"]
        password = request.POST["password"]
        no_ktp = request.POST["no_ktp"]
        raw_ttl = request.POST["ttl"]
        no_hp = request.POST["no_hp"]
        alamat = request.POST["alamat"]
        kategori = request.POST["kategori"]
        pekerjaan = request.POST["pekerjaan"]

        user = user_obj.create_pelanggan_penyewa(
            name, password, no_ktp, alamat, raw_ttl, email, no_hp, kategori, pekerjaan)

    return redirect("user:list_pengguna")


@login_required
def logout_pelanggan(request):
    try:
        # del request.session['staff']
        del request.session['user']
    except KeyError:
        pass
    return redirect("user:landing")


@login_required
def profile(request, id):

    user = Pelanggan().get_profile(id)

    print(user)

    return render(request, "user_handle/profile.html", {
        "user": user
    })


def list_mitra_bank(request):

    bank = Bank().getAll()

    return render(request, "user_handle/list_bank.html", {
        "list_bank": bank
    })


def add_mitra_bank(request):

    if request.method == "POST":

        bank_obj = Bank()

        nama_bank = request.POST["nama"]
        bank_obj.create_mitra(nama_bank)

    return redirect("user:list_bank")


def delete_bank(request, id):

    print("hai")
    Bank().delete_mitra(id)

    return redirect("user:list_bank")

templates/user_handle/list_bank.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/list_pengguna.css' %}">
{% endblock style %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}


{% block body %}
<div class="page-container" id="list">
    <div class="container">
        <form method="POST" action="{% url 'user:add_bank' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_email">Tambah Mitra Baru</label>
                <input id="id_email" type="text" class="form-control" name="nama" required>
                <small id="emailHelp" class="form-text text-muted">Masukkan Nama Bank.</small>
                <button type="submit" class="nav-link btn white bg-blue">Tambah</button>
            </div>
        </form>
    </div>
    <div class="tab-pane fade show active" id="table3" role="tabpanel" aria-labelledby="home-tab">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Kode</th>
                    <th scope="col">Nama Bank</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for b in list_bank %}
                <tr>
                    <th scope="row">{{b.kode_bank}}</th>
                    <td>{{b.nama_bank}}</td>
                    <td><a class="nav-link btn white bg-red"
                            href="{% url 'user:delete_bank' id=b.kode_bank %}">Hapus</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock body %}

templates/user_handle/list_pengguna.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/list_pengguna.css' %}">
{% endblock style %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}

{% block body %}
<div class="page-container" id="list">

    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#table" role="tab" aria-controls="home"
                aria-selected="true">Pemilik Lukisan</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#table2" role="tab" aria-controls="profile"
                aria-selected="false">Penyewa Lukisan</a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="table" role="tabpanel" aria-labelledby="home-tab">
            <div class="action-box">
                <button class="nav-link white flat-red" data-toggle="modal" data-target="#daftarModal"
                    type="button">Tambah
                    Akun
                    Pemilik</button>
            </div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">ID Pelanggan</th>
                        <th scope="col">No KTP</th>
                        <th scope="col">Nama</th>
                        <th scope="col">Alamat</th>
                        <th scope="col">Tanggal Lahir</th>
                        <th scope="col">No HP</th>
                        <th scope="col">Email</th>
                        <th scope="cocoll">No Rek</th>
                        <th scope="col">Nama Bank</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pemilik in list_pemilik %}
                    <tr>
                        <th scope="row">{{pemilik.id_pelanggan}}</th>
                        <td>{{pemilik.no_ktp}}</td>
                        <td>{{pemilik.nama}}</td>
                        <td>{{pemilik.alamat}}</td>
                        <td>{{pemilik.tempat_tgl_lahir}}</td>
                        <td>{{pemilik.no_hp}}</td>
                        <td>{{pemilik.email}}</td>
                        <td>{{pemilik.no_rek}}</td>
                        <td>{{pemilik.nama_bank}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane fade" id="table2" role="tabpanel" aria-labelledby="profile-tab">
            <div class="action-box">
                <button class="nav-link white flat-red" data-toggle="modal" data-target="#daftarPenyewaModal"
                    type="button">Tambah
                    Akun
                    Penyewa</button>
            </div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">ID Pelanggan</th>
                        <th scope="col">No KTP</th>
                        <th scope="col">Nama</th>
                        <th scope="col">Alamat</th>
                        <th scope="col">Tanggal Lahir</th>
                        <th scope="col">No HP</th>
                        <th scope="col">Email</th>
                        <th scope="cocoll">Pekerjaan</th>
                        <th scope="col">Kategori</th>
                    </tr>
                </thead>
                <tbody>
                    {% for penyewa in list_penyewa %}
                    <tr>
                        <th scope="row">{{penyewa.id_pelanggan}}</th>
                        <td>{{penyewa.no_ktp}}</td>
                        <td>{{penyewa.nama}}</td>
                        <td>{{penyewa.alamat}}</td>
                        <td>{{penyewa.tempat_tgl_lahir}}</td>
                        <td>{{penyewa.no_hp}}</td>
                        <td>{{penyewa.email}}</td>
                        <td>{{penyewa.pekerjaan}}</td>
                        <td>{{penyewa.kategori}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Modal Daftar Pemilik -->
<div class="modal fade" id="daftarModal" tabindex="-1" role="dialog" aria-labelledby="daftarModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="daftarModalLabel">Daftar akun Pemilik Lukisan SiPelu</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="{% url 'user:signup_pemilik' %}">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_nama">Nama</label>
                        <input id="id_nama" type="text" class="form-control" name="nama" maxlength="200" required>
                        <small id="emailHelp" class="form-text text-muted">Masukkan Nama.</small>
                    </div>
                    <div class="form-group">
                        <label for="id_email">Email</label>
                        <input id="id_email" type="text" class="form-control" name="email" required>
                        <small id="emailHelp" class="form-text text-muted">Masukkan email.</small>
                    </div>
                    <div class="form-group">
                        <label for="id_password">Password</label>
                        <input type="password" id="id_password" name="password" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="no_ktp">Nomor KTP</label>
                        <input id="id_ktp" type="text" pattern="[0-9]+" class="form-control" name="no_ktp"
                            maxlength="16" required>
                        <small id="emailHelp" class="form-text text-muted">Masukkan Nomor KTP.</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">Nama Bank</label>
                        <select class="form-control" id="exampleFormControlSelect1" name="bank">
                            {% for bank in list_bank%}
                            <option value="{{bank.nama_bank}}">{{bank.nama_bank}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="no_ktp">Nomor Rekening</label>
                        <input id="id_ktp" type="text" pattern="[0-9]+" class="form-control" name="no_rek" required>
                        <small id="emailHelp" class="form-text text-muted">Masukkan Nomor Rekening.</small>
                    </div>
                    <div class="form-group">
                        <label for="id_ttl">Tanggal Lahir</label>
                        <input type="date" id="id_ttl" name="ttl" class="form-control" pattern="\d{4}-\d{2}-\d{2}">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Nomor HP</label>
                        <input id="id_hp" type="text" pattern="[0-9]+" class="form-control" name="no_hp" maxlength="16"
                            required>
                        <small id="emailHelp" class="form-text text-muted">Masukkan Nomor HP.</small>
                    </div>
                    <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <textarea class="form-control" id="alamat" name="alamat" rows="3"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="nav-link btn white bg-blue">Tambah</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Modal Daftar pemilik -->

<!-- Modal Daftar Penyewa -->
<div class="modal fade" id="daftarPenyewaModal" tabindex="-1" role="dialog" aria-labelledby="daftarModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="daftarModalLabel">Daftar akun Penyewa Lukisan SiPelu</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="{% url 'user:signup_penyewa' %}">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_nama">Nama</label>
                        <input id="id_nama" type="text" class="form-control" name="nama" maxlength="200" required>
                        <small id="emailHelp" class="form-text text-muted">Masukkan Nama.</small>
                    </div>
                    <div class="form-group">
                        <label for="id_email">Email</label>
                        <input id="id_email" type="text" class="form-control" name="email" required>
                        <small id="emailHelp" class="form-text text-muted">Masukkan email.</small>
                    </div>
                    <div class="form-group">
                        <label for="id_password">Password</label>
                        <input type="password" id="id_password" name="password" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="no_ktp">Nomor KTP</label>
                        <input id="id_ktp" type="text" pattern="[0-9]+" class="form-control" name="no_ktp"
                            maxlength="16" required>
                        <small id="emailHelp" class="form-text text-muted">Masukkan Nomor KTP.</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">Kategori</label>
                        <select class="form-control" id="exampleFormControlSelect1" name="kategori">
                            <option value="B">B</option>
                            <option value="S">S</option>
                            <option value="P">P</option>
                            <option value="G">G</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="no_ktp">Pekerjaan</label>
                        <input id="id_ktp" type="text" class="form-control" name="pekerjaan" required>
                        <small id="emailHelp" class="form-text text-muted">Masukkan Nama Pekerjaan.</small>
                    </div>
                    <div class="form-group">
                        <label for="id_ttl">Tanggal Lahir</label>
                        <input type="date" id="id_ttl" name="ttl" class="form-control" pattern="\d{4}-\d{2}-\d{2}">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Nomor HP</label>
                        <input id="id_hp" type="text" pattern="[0-9]+" class="form-control" name="no_hp" maxlength="16"
                            required>
                        <small id="emailHelp" class="form-text text-muted">Masukkan Nomor HP.</small>
                    </div>
                    <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <textarea class="form-control" id="alamat" name="alamat" rows="3"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="nav-link btn white bg-blue">Tambah</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Modal Daftar penyewa -->
{% endblock body %}

templates/user_handle/list_staff.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/list_pengguna.css' %}">
{% endblock style %}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}


{% block body %}
<div class="page-container" id="list">
    <div class="tab-pane fade show active" id="table3" role="tabpanel" aria-labelledby="home-tab">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">No Staff</th>
                    <th scope="col">Nama</th>
                    <th scope="col">Tanggal Lahir</th>
                    <th scope="col">No HP</th>
                    <th scope="col">Email</th>
                    <th scope="cocoll">Lulusan</th>
                </tr>
            </thead>
            <tbody>
                {% for staff in list_staff %}
                <tr>
                    <th scope="row">{{staff.no_staff}}</th>
                    <td>{{staff.nama}}</td>
                    <td>{{staff.tempat_tgl_lahir}}</td>
                    <td>{{staff.no_hp}}</td>
                    <td>{{staff.email}}</td>
                    <td>{{staff.lulusan_staff}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock body %}

templates/user_handle/profile.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock style %}


{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}


{% block body %}
<div class="page-container" id="profile">
    <div class="container-card" id="data-profile">
        {% if is_staff%}
        <h1>Profil Staff</h1>
        <h4>No Staff: {{user.no_staff}}</h4>
        {% else %}
        <h1>Profil Pelanggan</h1>
        <h4>No Id: {{user.id_pelanggan}}</h4>
        {% endif %}
        <h4>Nama: {{user.nama}}</h4>
        <h4>Email: {{user.email}}</h4>
        <h4>No Hp: {{user.no_hp}}</h4>
        <h4>Tanggal Lahir: {{user.tempat_tgl_lahir}}</h4>
    </div>

</div>
{% endblock body %}