lukisan_handle/urls.py
from django.urls import path, include
from .views import *

app_name = "lukisan"

urlpatterns = [
    path('lukisan/<id>', lukisan_detail, name="detail"),
    path('list_sewa', list_sewa, name="list_sewa"),
    path('list_transaksi', list_transaksi, name="list_transaksi")
]

sipelu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user_handle.urls")),
    path('detail/', include("lukisan_handle.urls"))
]

user_handle/urls.py
from django.urls import path, include
from .views import *

app_name = "user"

urlpatterns = [
    path('', landing, name="landing"),

    path('login_staff', login_staff, name="login_staff"),
    path('logout_staff', logout_staff, name="logout_staff"),
    path('list_pengguna', list_pengguna, name="list_pengguna"),
    path('list_staff', list_staff, name="list_staff"),
    path('list_bank', list_mitra_bank, name="list_bank"),
    path('add_bank', add_mitra_bank, name="add_bank"),
    path('delete_bank/<id>', delete_bank, name="delete_bank"),

    path('login', login_pelanggan, name="login"),
    path('logout', logout_pelanggan, name="logout"),
    path('signup_pemilik', daftar_pelanggan_pemilik, name="signup_pemilik"),
    path('signup_penyewa', daftar_pelanggan_penyewa, name="signup_penyewa"),
    path('profile_staff/<id>', profile_staff, name="profile_staff"),
    path('profile/<id>', profile, name="profile")
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Quicksand:400,500,600,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block style %}

    {% endblock style %}

    <title>Sipelu</title>
</head>

<body>

    {% block navbar %}

    {% endblock navbar %}

    {% block body %}

    {% endblock body %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>

    {% block js %}

    {% endblock js %}

</body>

</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg" id="navbar">
    <a class="navbar-brand blue" href="{% url 'user:landing' %}"><b>SiPelu</b></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <!-- <span class="navbar-toggler-icon"></span> -->
        <div id="top" class="bg-red"></div>
        <div id="bottom" class="bg-blue"></div>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
                {% url 'user:landing' as url %}
                <a href="{{ url }}" {% if request.path == url %} class="nav-link blue active" {% else %}
                    class="nav-link blue" {% endif %}>Katalog<span class="sr-only">(current)</span></a>
            </li>
            {% if is_auth %}

            {% if is_staff%}
            <li class="nav-item">
                {% url 'lukisan:list_sewa' as url %}
                <a href="{{ url }}" {% if request.path == url %} class="nav-link blue active" {% else %}
                    class="nav-link blue" {% endif %}>Sewa<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                {% url 'lukisan:list_transaksi' as url %}
                <a href="{{ url }}" {% if request.path == url %} class="nav-link blue active" {% else %}
                    class="nav-link blue" {% endif %}>Transaksi<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                {% url 'user:list_pengguna' as url %}
                <a href="{{ url }}" {% if request.path == url %} class="nav-link blue active" {% else %}
                    class="nav-link blue" {% endif %}>Pengguna<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                {% url 'user:list_staff' as url %}
                <a href="{{ url }}" {% if request.path == url %} class="nav-link blue active" {% else %}
                    class="nav-link blue" {% endif %}>Staff<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                {% url 'user:list_bank' as url %}
                <a href="{{ url }}" {% if request.path == url %} class="nav-link blue active" {% else %}
                    class="nav-link blue" {% endif %}>Bank<span class="sr-only">(current)</span></a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link blue" href="{% url 'user:landing' %}">Transaksi<span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link blue" href="{% url 'user:landing' %}">Galeri<span
                        class="sr-only">(current)</span></a>
            </li>
            {% endif %}

            {% if is_pemilik %}
            <li class="nav-item">
                <a class="nav-link blue" href="{% url 'user:landing' %}">Daftar TerSewa<span
                        class="sr-only">(current)</span></a>
            </li>
            {% endif %}

            {% endif %}
        </ul>
        {% if not is_auth %}
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0" id="user-system">

            <li class="nav-item user">
                <button class="nav-link white flat-blue" data-toggle="modal" data-target="#masukPelangganModal"
                    type="button">Masuk</button>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0" id="user-system">
            {% if is_staff %}
            <li class="nav-link nav-item user">
                <a class="" href="{% url 'user:profile_staff' id=is_auth.no_staff %}">Hei,{{is_auth.nama}}!</a>
            </li>
            <li class="nav-item user">
                <a class="nav-link white flat-red" href="{% url 'user:logout_staff' %}">Keluar</a>
            </li>
            {% else %}
            <li class="nav-link nav-item user">
                <a class="" href="{% url 'user:profile' id=is_auth.id_pelanggan %}">Hei,{{is_auth.nama}}!</a>
            </li>
            <li class="nav-item user">
                <a class="nav-link white flat-red" href="{% url 'user:logout' %}">Keluar</a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
    </div>
</nav>

<!-- Modal Masuk pelanggan -->
<div class="modal fade" id="masukPelangganModal" tabindex="-1" role="dialog" aria-labelledby="masukPelangganModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="masukModalLabel">Masuk ke Akun SiPelu</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="{% url 'user:login' %}" id="staff_login">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">ID Pelanggan</label>
                        <input id="id_pelanggan_id" type="text" class="form-control" name="user_id" maxlength="10"
                            required>
                        <small id="emailHelp" class="form-text text-muted">Masukkan Id Pelanggan anda.</small>
                        <small id="emailHelp" class="form-text text-muted">
                            Anda Staff?
                            <button type="button" class="btn-special" data-toggle="modal" data-target="#masukModal"
                                data-dismiss="modal">Masuk</button>
                        </small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" id="id_password" name="password" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="nav-link white flat-orange" data-toggle="modal"
                        data-target="#daftarModal" data-dismiss="modal">Daftar</button>
                    <button type="submit" class="nav-link btn white bg-blue">Masuk</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Modal Masuk pelanggan -->

<!-- Modal Masuk staff -->
<div class="modal fade" id="masukModal" tabindex="-1" role="dialog" aria-labelledby="daftarModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="masukModalLabel">Masuk ke Akun SiPelu</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="{% url 'user:login_staff' %}" id="staff_login">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">ID Staff</label>
                        <input id="id_staff_id" type="text" class="form-control" name="staff_id" maxlength="10"
                            required>
                        <small id="emailHelp" class="form-text text-muted">Masukkan Id Staff anda.</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" id="id_password" name="password" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="nav-link white flat-orange" data-toggle="modal"
                        data-target="#daftarModal" data-dismiss="modal">Daftar</button>
                    <button type="submit" class="nav-link btn white bg-blue">Masuk</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Modal Masuk staff -->