lukisan_handle/urls.py
from django.urls import path, include
from .views import *

app_name = "lukisan"

urlpatterns = [
    path('lukisan/<id>', lukisan_detail, name="detail"),
    path('list_sewa', list_sewa, name="list_sewa"),
    path('list_transaksi', list_transaksi, name="list_transaksi")
]

sipelu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("user_handle.urls")),
    path('detail/', include("lukisan_handle.urls"))
]

templates/landing/landing.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
<link rel="stylesheet" href="{% static 'css/landing.css' %}">
{% endblock style %}


{% block navbar %}
{% include 'navbar.html' %}
{% endblock navbar %}


{% block body %}
<div class="page-container" id="landing">
    <div class="container" id="content">
        <div>
            <h3>Daftar Lukisan</h3>
        </div>
        <div id="list-lukisan">
            {% for l in lukisan %}
            {% include 'landing/lukisan.html' with data=l %}
            {% endfor %}
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if lukisan.has_previous %}
                <a href="?page=1" class="red">&laquo; Pertama</a>
                <a href="?page={{ lukisan.previous_page_number }}" class="red">Sebelumnya</a>
                {% endif %}

                <span class="current blue">
                    Halaman {{ lukisan.number }} dari {{ lukisan.paginator.num_pages }}.
                </span>

                {% if lukisan.has_next %}
                <a href="?page={{ lukisan.next_page_number }}" class="red">Selanjutnya</a>
                <a href="?page={{ lukisan.paginator.num_pages }}" class="red">Terakhir &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>

    <div class="container-card" id="profile">
        <div class="container">
            <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
        </div>
    </div>
</div>
{% endblock body %}

templates/landing/lukisan.html
{% load static %}

<div class="container-card" id="lukisan">
    <div id="lukisan-detail">
        <div>
            <span>Nama : {{data.nama_lukisan}}</span>
        </div>
        <div>
            <span>Tahun : {{data.tahun}}</span>
        </div>
        <div>
            <span>Tema : {{data.tema_lukisan}}</span>
        </div>
        <div>
            <span>Harga : Rp {{data.harga}}</span>
        </div>
    </div>
    <div id="lukisan-action">
        <a class="btn flat-blue" href="{% url 'lukisan:detail' id=data.id_lukisan %}">Detail</a>
    </div>
</div>

templates/landing/test.html
{% extends 'base.html' %}


{% block body %}
<div class="jumbotron">
    <h1>Hai</h1>
</div>
{% endblock body %}